# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  matlab: mathworks/matlab@0
  aws-cli: circleci/aws-cli@3

executors:
  ubuntu:
    machine:
      image: 'ubuntu-2204:2022.04.1' # if you change version you may need to update the command installing OCTAVE dependencies
      resource_class: medium

    environment:
      GITHUB_WORKSPACE: /home/circleci/tools/reproanalysis
      AWS_ACCESS_KEY_ID: anonymus
      AWS_SECRET_ACCESS_KEY: anonymus
      AWS_DEFAULT_REGION: eu-west-2
      AWS_EC2_METADATA_DISABLED: true

commands:
  testubuntuoctave:
    description: "Testing on Ubuntu using OCTAVE"
    parameters:
      parameter_xml: 
        type: string
        default: parameters_circleci.xml
      load_fsl:
        type: integer
        default: 0
      load_freesurfer:
        type: integer
        default: 0
      command:
        type: string
        default: reproaClose()
    steps:
      - run: 
          name: Checkout with submodules
          command: git clone --recurse-submodule "$CIRCLE_REPOSITORY_URL" "$GITHUB_WORKSPACE"

      - run: 
          name: Build and install OCTAVE
          command: |           
            export DEBIAN_FRONTEND=noninteractive
            sudo apt remove needrestart
            sudo apt update
            sudo apt install gcc g++ autoconf automake bison dvipng epstool fig2dev flex gfortran gnuplot-x11 gperf gzip icoutils libarpack2-dev libbison-dev libopenblas-dev libcurl4-gnutls-dev libfftw3-dev libfltk1.3-dev libfontconfig1-dev libfreetype6-dev libgl1-mesa-dev libgl2ps-dev libglpk-dev libgraphicsmagick++1-dev libhdf5-dev liblapack-dev libosmesa6-dev libpcre3-dev libqhull-dev libqscintilla2-qt5-dev libqrupdate-dev libreadline-dev librsvg2-bin libsndfile1-dev libsuitesparse-dev libsundials-dev libtool libxft-dev make openjdk-8-jdk perl portaudio19-dev pstoedit qtbase5-dev qttools5-dev qttools5-dev-tools rapidjson-dev rsync tar texinfo texlive-latex-extra zlib1g-dev -y
            mkdir ~/install-octave
            cd ~/install-octave
            wget https://ftp.gnu.org/gnu/octave/octave-7.3.0.tar.gz
            tar -xzf octave-7.3.0.tar.gz
            rm octave-7.3.0.tar.gz
            cd octave-7.3.0
            mkdir .build
            cd .build
            ./../configure --prefix=$HOME/tools/octave
            make -j2
            make check
            make install

      - run:
          name: Install tools and configure aa
          command: |          
            mkdir ~/.reproa
            cd $GITHUB_WORKSPACE/.circleci
            cp << parameters.parameter_xml >> ~/.reproa/reproa_parameters_user.xml
            sudo apt-get update
            sudo apt install python2
            sudo ln -s /usr/bin/python2 /usr/bin/python
            python trigger_install.py
            sudo apt install libopencv-dev libavformat-dev libavcodec-dev libswscale-dev
            sudo apt install liboctave-dev
            cd ~/tools/spm12/src
            make PLATFORM=octave
            make PLATFORM=octave install
          environment:
            LOAD_FSL: << parameters.load_fsl >>
            LOAD_FREESURFER: << parameters.load_freesurfer >>
            PARAMETER_XML: << parameters.parameter_xml >>      

      - run:
          name: Run test
          command: |
            echo "addpath(getenv('GITHUB_WORKSPACE')); reproaSetup(); << parameters.command >>" > ~/test_run.m
            $HOME/tools/octave/bin/octave-cli ~/test_run.m
          no_output_timeout: 3h

      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/output
            cp $GITHUB_WORKSPACE/tests/reproa.log /tmp/output
            cp -R $GITHUB_WORKSPACE/tests/report /tmp/output
            tar -czf /tmp/output.tar.gz /tmp/output
      - store_artifacts:
          destination: report
          path: /tmp/output.tar.gz

  testubuntumatlab:
    description: "Testing on Ubuntu using MATLAB"
    parameters:
      parameter_xml: 
        type: string
        default: parameters_circleci.xml
      load_fsl:
        type: integer
        default: 0
      load_freesurfer:
        type: integer
        default: 0
      command:
        type: string
        default: reproaClose()
    steps:
      - run: 
          name: Checkout with submodules
          command: git clone --recurse-submodule "$CIRCLE_REPOSITORY_URL" "$GITHUB_WORKSPACE"

      - matlab/install:
          release: R2020a # comes with Python 2.7

      - run:
          name: Install tools and configure aa
          command: |
            mkdir ~/.reproa
            cd $GITHUB_WORKSPACE/.circleci
            cp << parameters.parameter_xml >> ~/.reproa/reproa_parameters_user.xml
            python trigger_install.py
          environment:
            LOAD_FSL: << parameters.load_fsl >>
            LOAD_FREESURFER: << parameters.load_freesurfer >>
            PARAMETER_XML: << parameters.parameter_xml >>

      - aws-cli/setup:
          profile-name: example

      - matlab/run-command:
          command: addpath(getenv('GITHUB_WORKSPACE')); reproaSetup(); << parameters.command >>
          no-output-timeout: 3h
      
      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/output
            cp $GITHUB_WORKSPACE/tests/reproa.log /tmp/output
            cp -R $GITHUB_WORKSPACE/tests/report /tmp/output
            tar -czf /tmp/output.tar.gz /tmp/output
      - store_artifacts:
          destination: report
          path: /tmp/output.tar.gz

jobs:
  usecase_SPM:
    executor: ubuntu
    steps:
      - testubuntuoctave:
          parameter_xml: parameters_circleci_minimal_ubuntu.xml
          command: testRun('test_MoAEpilot_fmri','SPM_CH30')

workflows:
  build:
    jobs:
      - usecase_SPM:
          context: aws